### ISSUE TITLE
Reply to messages?

### ISSUE THREAD

**Issue by chrisopedia** [fspinillo/slackfred#1]
Not sure if this is something you'd consider doing, or is even possible with the Slack API.  It would be awesome if you were able to allow for messages via Slackfred so when seeing a notification of a message you could type `slk #general 'message'` to message a room or `slk @user 'message'` to message a user.

**Comment by Cmdv** [comment]
great workflow but yes a post/reply to messages would make it a superb workflow

**Comment by fspinillo** [comment]
The latest workflow supports sending messages to channels if you'd like to give it a try!
