### ISSUE TITLE
Private channels in the search

### ISSUE THREAD

**Issue by stop777** [fspinillo/slackfred#10]
Trying to use "slk" to navigate to a private channel but it is not showing.
![2015-04-09 18-01-25 slack](https://cloud.githubusercontent.com/assets/144782/7069646/84b42e28-dee2-11e4-9ade-6e9ce3f65e31.png)
![2015-04-09 18-01-38 2015-04-09 18-01-25 slack png](https://cloud.githubusercontent.com/assets/144782/7069647/859668ba-dee2-11e4-83e0-a04ca7d2e120.png)

**Comment by fspinillo** [comment]
Channel/member search only supports public groups, but I'll be adding private channel support soon.

**Comment by fspinillo** [comment]
This has been added and is in the current build. Cheers!
