### ISSUE TITLE
slf: Error in workflow

### ISSUE THREAD

**Issue by michaellopez** [fspinillo/slackfred#11]
I get an error with `slf` sometimes.

```
workflow.py:1971 DEBUG    get_password : fspinillo.alfredv2.slackfred:slack_api_key
workflow.py:1495 DEBUG    Loading cached data from : /Users/[username]/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/fspinillo.alfredv2.slackfred/files.cpickle
workflow.py:1830 ERROR    'initial_comment'
Traceback (most recent call last):
  File "/Users/[username]/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.9B240993-02D7-4BF2-820F-CB174330F081/workflow/workflow.py", line 1828, in run
    func(self)
  File "slackfred-files.py", line 47, in main
    subtitle = files['initial_comment']['comment'],
KeyError: 'initial_comment'
```

Seems that the data from the API does not contain something the workflow expects.

Sometimes it works, meaning the API returns as the workflow expects.

**Comment by fspinillo** [comment]
That line is looking for any files that have comments attached them. It's working fine on my end and I checked it against the tester to see if anything has changed. If you go [here](https://api.slack.com/methods/files.list) can you check it against your team and see if anything comes back with comments?

**Comment by michaellopez** [comment]
@fspinillo Yeah ok. But some of our files do not have the initial comment (meaning the comment that was written when the files was first posted) we leave that blank sometimes. So the API returns files without `initial_comment` if that was not given when posting a file.

Using [Tester](https://api.slack.com/methods/files.list/test) I get files with `initial_comment` and files without `initial_comment`.

**Comment by michaellopez** [comment]
@fspinillo The workflow should be able to handle files without `initial_comment` is what I am hoping for :)

**Comment by fspinillo** [comment]
I put the initial_comment call in there to be able to make that searchable and if there is no comment it should still display the files in the list.

I removed the initial_comment call, let me know if this works for you: http://d.pr/f/15kin

**Comment by michaellopez** [comment]
@fspinillo Yeah, that works better. Is any functionality lost now with its removal?

Can't it conditional? If it is there you can use it like you wanted, if it is not it is ignored?

**Comment by fspinillo** [comment]
The only functionality lost is if someone uploads a file with a comment you wont see the comment. If you view the source it's just a basic if statement to check for a comment count and if the comment count is higher than 0 it will also load the associated comment with it. Otherwise it falls back to just displaying the file name in the results.

**Comment by michaellopez** [comment]
@fspinillo I'm not sure this is the best fix. I'll dig a bit more and get back with a PR.
