### ISSUE TITLE
Wrong icon on packal?

### ISSUE THREAD

**Issue by vitorgalvao** [fspinillo/slackfred#15]
Seems to be based on Wunderlist instead of Slack. Is that intentional?

![](http://i.imgur.com/fY17Qtk.png)

**Comment by fspinillo** [comment]
Definitely wasn't intentional and I'm not sure where that icon is even from. I'll update it now, thanks. Looks like one of yours is showing the wrong icon as well http://www.packal.org/workflow/appfreeze

**Comment by vitorgalvao** [comment]
Ah, definitely a bug on packal’s side, then. Will fix it as well, thank you.

**Comment by shawnrice** [comment]
Updating some random module on the backend caused this problem to manifest at some point. Basically, it happens now when there are the same file names for images (and everyone has 'icon.png' to upload as the icon). This wasn't the case before whichever module updated and messed up the site.

I've been going back and fixing them manually while working on a more comprehensive solution.

Anyway, I went in and fixed the icon, so it should be correct now.

**Comment by fspinillo** [comment]
Thanks Shawn!
