### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by RashidGilanpour** [fspinillo/slackfred#16]
Thanks for making this Frank 
Is there any chance you would consider adding a workflow/script that would allow for posting to a slack channel. I'd love to be able to share what I'm working on with my team by typing "on" then the text and have it post to a specific channel. 

Thank you

**Comment by fspinillo** [comment]
Do you mind grabbing the latest workflow file from the workflow folder and test out message sending for me? Currently the way it works is as follows:

Open alfred  
type slm  
Select the channel with your arrow keys and hit tab  
Type your message and hit send

I'm still trying to work out having type ahead for channels, but the basic functionality is there

**Comment by RashidGilanpour** [comment]
Cool! seems to work great

I did notice that it's missing the functionality of highlighting the channel letting all users know that the channel has a new post.

:)

**Comment by RashidGilanpour** [comment]
Cool! seems to work great

I did notice that it's missing the functionality of highlighting the
channel letting all users know that the channel has a new post.

:)




*Rashid Gilanpour*
*See my roles » <https://glassfrog.holacracy.org/people/14447>*
HolacracyOne, LLC
Exquisite Organization
Office: 213.973.2012
Schedule a Meeting <http://www.pick.co/@rashid.gilanpour>
www.holacracy.org <http://holacracy.org/>

<http://www.linkedin.com/company/holacracyone-llc/>
<http://www.youtube.com/user/HolacracyOne>
<http://www.facebook.com/HolacracyOne> <http://twitter.com/HolacracyOne/>


*The Holacracy book is now available! Order <http://www.holacracybook.com>
now to discover a better way of working!*

**Comment by fspinillo** [comment]
Looking at the docs I'm not seeing anything that would indicate how to handle that. I think it might just be the way it's implemented on their end.

**Comment by RashidGilanpour** [comment]
gotcha thanks :)
