### ISSUE TITLE
Change teams

### ISSUE THREAD

**Issue by buzali** [fspinillo/slackfred#17]
Although `slk X` shows me all channels and users of all my configured Slack teams, slackfred does not change teams when selecting a channel/user that is not from the active team on Slack.
Any way to fix?

An idea would be to tell slackfred the order of the teams to allow it to use the shortcut `⌘+team#` to switch teams.

**Comment by fspinillo** [comment]
Let me do some digging. I know Slack has a URL scheme, but I can't find any documentation right now.
