### ISSUE TITLE
Unreliable search

### ISSUE THREAD

**Issue by justinhelmer** [fspinillo/slackfred#19]
First of all, great tool. Really enables productivity.

That being said, I am unfortunately unable to use the search functions. The other functions work correctly, including the image search, but the name search and text search are generally speaking, unusable.

The behavior is such that as you begin typing, the query occurs, but then the default pane ("search google", etc) gets rendered instead of the results. Usually when there are no results, that pane is soon replaced by the text "no results found." I can live with the temporary default results being displayed.

However, when there *should* be results, nothing displays other than the defaults. I validated the authentication, and that the script generates the URLs correctly. The query works and returns JSON data, so it's just a display issue with the script.

Any help would be greatly appreciated.

**Comment by fspinillo** [comment]
Are you by any chance in a free Slack group? I'm noticing for one of my groups if I have an IM history that is older than the 10,000 free messages then no results will be returned.

If you do a text search (sls) with the debugger open, what is returned in the window?

**Comment by justinhelmer** [comment]
Good thought, but when I hit the API directly (through a REST client or browser), I get results for the same searches. For some reason, on those calls, it seems like the script is having issues with authentication.

When using `sls [exists]`:
```
[STDERR: alfred.workflow.input.scriptfilter] 10:38:39 workflow.py:1971 DEBUG    get_password : fspinillo.alfredv2.slackfred:slack_api_key
[STDERR: alfred.workflow.input.scriptfilter] 10:38:43 workflow.py:1971 DEBUG    get_password : fspinillo.alfredv2.slackfred:slack_api_key
[STDERR: alfred.workflow.input.scriptfilter] 10:38:44 workflow.py:1971 DEBUG    get_password : fspinillo.alfredv2.slackfred:slack_api_key
[STDERR: alfred.workflow.input.scriptfilter] 10:38:49 workflow.py:1971 DEBUG    get_password : fspinillo.alfredv2.slackfred:slack_api_key
[STDERR: alfred.workflow.input.scriptfilter] 10:38:50 workflow.py:1971 DEBUG    get_password : fspinillo.alfredv2.slackfred:slack_api_key
```

However, as I mentioned, other calls work just fine. When using `slm`, for example, you can see a successful cache:

```
10:39:08 workflow.py:1531 DEBUG    Cached data saved at : /Users/justin/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/fspinillo.alfredv2.slackfred/channels.cpickle
[STDERR: alfred.workflow.input.scriptfilter] 10:39:08 workflow.py:1495 DEBUG    Loading cached data from : /Users/justin/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/fspinillo.alfredv2.slackfred/channels.cpickle
```

**Comment by fspinillo** [comment]
Hm, I think I might know what is going on. That particular workflow call is using requests instead of the built in web call from the workflow library. I wonder if it's not importing it properly when it runs.

If you right click on the workflow and do open in finder do you see a folder in there for "requests"?

**Comment by justinhelmer** [comment]
@fspinillo - There is in fact a `requests` folder inside the workflow directory. In regards to the more elaborated output, here is the entire log when running `sls earthquake`, where `earthquake` is a term that was just recently added to chat history:

```
[STDERR: alfred.workflow.input.scriptfilter] 12:36:27 workflow.py:1971 DEBUG    get_password : fspinillo.alfredv2.slackfred:slack_api_key
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items />
[STDERR: alfred.workflow.input.scriptfilter] 12:36:28 workflow.py:1971 DEBUG    get_password : fspinillo.alfredv2.slackfred:slack_api_key
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>No search results found</title><subtitle>Wanclouds</subtitle></item></items>
[STDERR: alfred.workflow.input.scriptfilter] 12:36:29 workflow.py:1971 DEBUG    get_password : fspinillo.alfredv2.slackfred:slack_api_key
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items />
```

Also, just to reiterate, the API request is successful when hit directly.
`/api/search.messages?token=[token]&query=earthquake&count=10&pretty=1`:

```
{
    "ok": true,
    "query": "earthquake",
    "messages": {
        "total": 1,
        "pagination": {
            "total_count": 1,
            "page": 1,
            "per_page": 10,
            "page_count": 1,
            "first": 1,
            "last": 1
        },
        "paging": {
            "count": 10,
            "total": 1,
            "page": 1,
            "pages": 1
        },
        "matches": [
            {
                "type": "group",
                "user": "[user.id]",
                "username": "[user.username]",
                "ts": "1451152660.000004",
                "text": "its been good....very cold and 6.9 intensity earthquake where I am staying",
                "channel": {
                    "id": "[channel.id]",
                    "name": "chai"
                },
                "permalink": "...",
                "previous": {},
                "previous_2": {},
                "next": {},
                "next_2": {}
            }
        ]
    }
}
```
I really appreciate your time on this.

**Comment by fspinillo** [comment]
That JSON response helped. Right now the message search is only for public channels and that result you posted is for a private group. I'm going to make some tweaks and I'll respond when I have it sorted out.

**Comment by fspinillo** [comment]
Grab the latest file and give it a go.

**Comment by justinhelmer** [comment]
Works perfectly. Thanks so much for putting this together. My new favorite workflow :-)

**Comment by justinhelmer** [comment]
Also you can add `10.11` to the list of compatible OSes on the [Packal](http://www.packal.org/workflow/slackfred) page
