### ISSUE TITLE
slm doesn't exist in the workflow

### ISSUE THREAD

**Issue by schutzsmith** [fspinillo/slackfred#22]
I see you documented being able to use slm to send messages but it doesn't seem to exist in the actual workflow. Typing slm just brings up browser search because that doesn't exist.

**Comment by fspinillo** [comment]
Can you re-download the file from the /workflow folder and try again? Looks like during the merge the workflows went out of sync.

**Comment by schutzsmith** [comment]
Sure thing - thanks!
