### ISSUE TITLE
Does this extension autoupdate?

### ISSUE THREAD

**Issue by rohanpai** [fspinillo/slackfred#23]
I'm looking through your code and don't see anything that makes this workflow autoupdate.

**Comment by fspinillo** [comment]
Auto-update how? The script cahces the data for X minutes and then will re-cache it on the next command trigger.

**Comment by ragrum** [comment]
I guess it's about autoupdating itself to a newer version when available.

**Comment by fspinillo** [comment]
No, it does not auto-update. If you use Packal for getting the releases I believe that will notify you of updates.
