### ISSUE TITLE
slt command takes me to the wrong url

### ISSUE THREAD

**Issue by jerome-toole** [fspinillo/slackfred#24]
Following the install instructions, I type `slt` then `cmd+enter`. This took me to [https://api.slack.com/web](https://api.slack.com/web). There is not a list of teams on this page as mentioned. 

The page referred to in the guide seems to be https://api.slack.com/docs/oauth-test-tokens instead. Could this be changed?

**Comment by fspinillo** [comment]
D'oh. It was changed, but with having to revert changes because of V3 it must have been lost. I'll get it updated for both versions. Thanks!

**Comment by fspinillo** [comment]
just pushed up new workflow files if you want to grab them. Otherwise you can just update the URL yourself in the workflow settings.

**Comment by jerome-toole** [comment]
Thanks! I got in ok but thought it would be better without the guesswork.

On Wed, Jun 15, 2016 at 3:18 PM, Frank S. <notifications@github.com> wrote:

> D'oh. It was changed, but with having to revert changes because of V3 it
> must have been lost. I'll get it updated for both versions. Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fspinillo/slackfred/issues/24#issuecomment-226201397>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFRZOwjFRxrolyuMtHcWs72itiCWGKTjks5qMAnMgaJpZM4I2TMV>
> .
>



-- 
07963714722
@ <http://twitter.com/jamrone>jamrone
