### ISSUE TITLE
Clarify that you need to "generate test tokens" (I guess?) on the Slack API page

### ISSUE THREAD

**Issue by rootwork** [fspinillo/slackfred#26]
The setup instructions say:

> ...This will open up the Slack API page. Then look for your team (make sure you're logged in) near the bottom. If you already have a token, it will be next to your team name. If you haven't, click Create token.

Maybe that was true when this was first written, but it no longer displays tokens or the "Create token" buttons. Here's what it looks like:

![screen shot 2016-07-01 at 11 51 45 pm](https://cloud.githubusercontent.com/assets/79733/16538921/d1ed1c48-3fe6-11e6-8eb1-54844f0b39d7.png)

I take it I should go ahead and create those test tokens, because when I do so, _then_ I see a list of my organizations with "create token" buttons next to them.

So those instructions should be updated.

Thanks for building this great workflow!

**Comment by fspinillo** [comment]
Yes you are correct. I'll get the documentation updated.
