### ISSUE TITLE
Mute team notifications

### ISSUE THREAD

**Issue by Zianwar** [fspinillo/slackfred#27]
Hi, I love this workflow so far, before finding it, I was searching for away to mute a team notifications, I was thinking if its possible to add this feature?

**Comment by fspinillo** [comment]
Do you mean the do not disturb feature?

**Comment by Zianwar** [comment]
Yes!

**Comment by fspinillo** [comment]
Added in do-not-disturb support. Give it a shot for me: https://github.com/fspinillo/slackfred/releases/tag/1.8.3
