### ISSUE TITLE
Problem to auth token

### ISSUE THREAD

**Issue by macx** [fspinillo/slackfred#28]
I have created a token for my team and typed `stl API-TOKEN` (with the correct API token). Debugging your workflow I get this message:

```[2016-07-12 9:59:14 am][ERROR: action.script] 09:59:14 workflow.py:1941 DEBUG    Password exists : fspinillo.alfredv2.slackfred:slack_api_key
09:59:14 workflow.py:1971 DEBUG    get_password : fspinillo.alfredv2.slackfred:slack_api_key
09:59:14 workflow.py:1944 DEBUG    Password unchanged```

**Comment by fspinillo** [comment]
If you open up keychain access and search for alfredv2, are there any keys there?

**Comment by macx** [comment]
There was an entry. I deleted it and restart the setup again. Same result.

**Comment by fspinillo** [comment]
@macx the error displaying in the console is something in the library i'm using for Alfred. You can ignore it as it wont impact the workflow.
