### ISSUE TITLE
Individual users accounts come last in list

### ISSUE THREAD

**Issue by b-d-m-p** [fspinillo/slackfred#29]
Hi, 

Amazing workflow. 

So, here's my problem...

Say I slk for Jake and I get a list of all the chats that jake was in (i.e Jake, Bob, Rick & Jake, Mary, Tom) and then just the channel for Jake is at the bottom, so I have to hit the down arrow many times to get to just Jake, which makes it a bit inconvenient to use.  

It would be cool if the chat groups with one person came to the top because I am most likely going to be looking for that one, or if once I arrowed down to Jake and selected that that it would appear at the top because it was the last one selected. Either one of those will work for me. 

Is it possible to fix this issue? Hope that explanation makes sense.

Cheers,

Brett

**Comment by fspinillo** [comment]
Looks possible, let me see if I can get something fixed up.

**Comment by b-d-m-p** [comment]
Awesome!

**Comment by fspinillo** [comment]
Hey @b-d-m-p can you try a new release I pushed up https://github.com/fspinillo/slackfred/releases/tag/1.8.2

**Comment by b-d-m-p** [comment]
Awesome! Thanks so much!

**Comment by b-d-m-p** [comment]
Works perfectly! Cheers!
