### ISSUE TITLE
Token generation URL is out of date

### ISSUE THREAD

**Issue by modille** [fspinillo/slackfred#34]
The README says

> Open alfred and type `slt`, then paste your token. If you don't have a token, then hold `cmd` to open the API page to get one (look for your team near the bottom of the page).

And the command takes you to https://api.slack.com/web.

However, there's no form on that page for generating tokens anymore.

Slack seems to have replaced the simple token feature with OAuth 2.0.

I think the 2 options are:

1. Update Slackfred to point to the new URL for token generation (legacy), which is https://api.slack.com/custom-integrations/legacy-tokens
2. Switch from legacy tokens to creating a Slack application and using Client ID/Client Secret

**Comment by mauscoelho** [comment]
+1

**Comment by mistermark** [comment]
+1

**Comment by ppihus** [comment]
+1

**Comment by fspinillo** [comment]
I updated the URL and uploaded a new Workflow file for V3 -- https://github.com/fspinillo/slackfred/tree/master/workflow

**Comment by mauscoelho** [comment]
It worked :)
