### ISSUE TITLE
Support for multiple orgs?

### ISSUE THREAD

**Issue by zevav** [fspinillo/slackfred#5]
I'm active in three, so it'd be really handy!

**Comment by fspinillo** [comment]
Just wanted to give you an update that I'm currently updating the workflow to support multiple organizations where possible, plus throwing in some extras!

**Comment by zevav** [comment]
:+1:

**Comment by fspinillo** [comment]
This is pretty much ready, but was wondering if you would be willing to try it out and provide any feedback? I'm not using Slack much anymore so it's hard for me to give it a full go over prior to release, but I feel good about it. If so, can I reach you at the email address you provided?

**Comment by mstarkman** [comment]
I just installed this and I'm using slack with multiple orgs.  I'd me happy to give it a go for you.  mrstarkman at gmail dot com

**Comment by fspinillo** [comment]
This is in the current release. Please download and upgrade. Cheers

**Comment by zevav** [comment]
👍

Zev Averbach
Averbach Transcription
(212) 729-4850
www.avtranscription.com
