### ISSUE TITLE
Is it on the roadmap to mark unread messages as read in the desktop app?

### ISSUE THREAD

**Issue by axelson** [fspinillo/slackfred#6]
I'd like to be able to use Alfred to mark all unread messages as read in the desktop app, is that something that you would consider adding to slackfred?

**Comment by fspinillo** [comment]
Updated this to handle marking messages as read. Give it a shot and let me know if it's what you were thinking.

**Comment by axelson** [comment]
Thanks for this! Trying to setup slackfred now, but getting stuck on finding my token. Where on the https://api.slack.com/ page do I get my token? Do I need to create an application and go the oauth 2 route?

**Comment by fspinillo** [comment]
It looks like they changed the page up since I published this. There was a section at the bottom with tokens for each org. but it looks to be gone. I'll work on putting something in place and update.

**Comment by axelson** [comment]
Great! :+1:

**Comment by fspinillo** [comment]
A-ha! I found it.

Log into slack first, then go to this URL: https://api.slack.com/web

Scroll down to Auth. It should show your team(s).

**Comment by axelson** [comment]
Great! Got it to work. Although personally I modified the applescript to not hide slack afterward.

**Comment by fspinillo** [comment]
I'm going to work on trying to have it mark messages in the background. As for switching away, it's always hard to figure out which way people use Slack.

Glad it worked though!
